---
Author: Peter van der Windt
Title: 10 Things You Need to Know About the Local Average Treatment Effect
output: pdf_document
---

Sometimes when subjects do not receive the treatment to which they were assigned, the experimenter faces non-compliance. Some subjects may need the treatment so badly that they will always get treated, irrespective of whether they are assigned to the treatment or to the control group. These are called “Always-Takers”. Other subjects may not take the treatment even if they are assigned to the treatment group: the “Never-Takers”. Some subjects are “Compliers”. These are the subjects that do what they are supposed to do: they are treated when assigned to the treatment group, and they are not treated when they are assigned to the control group. Finally, some subjects act like teenagers and do the exact opposite of what they are supposed to do. They are called “Defiers”. Table 1 shows these four different types of subjects in the population.

```{r, echo = F, results = 'asis'}
library(xtable)
x <- sample(c(0, 1), 100, replace = T)
y <- sample(c(0, 1), 100, replace = T)
print(xtable(table(x, y)))
```

