---
output: 
  html_document:
    toc: true
    theme: journal
---

<!-- title: "10 Things to Know About Sampling" -->
<!-- author: "Methods Guide Author: Anna Wilke" -->

[Add introduction]
- define target population and elements in intro

1.	What is random sampling?
==

Random sampling, also referred to as probability sampling, is one way of selecting a sample of elements from a population. The key characteristic of random sampling is that each element in the population has a *known* and *non-zero* probability of being included in the sample. This goal is achieved by using some randomization mechanism -- be it a coin flip, a random number table, or a computer program -- to decide which elements of the population are going to be part of the sample. 

To make matters concrete, suppose that our target population consists of six elements:
$$U = \{1, 2, 3, 4, 5, 6\}$$
Imagine that we would like to draw a random sample of four elements from this population. There are 15 possible samples of this size that we may draw:
$$
\begin{aligned}
 S_1 & = \{1,2,3,4\} & S_6 & = \{1,2,5,6\} & S_{11} & = \{2,3,4,5\}\\
 S_2 & = \{1,2,3,5\} & S_7 & = \{1,3,4,5\} & S_{12} & = \{2,3,4,6\}\\
 S_3 & = \{1,2,3,6\} & S_8 & = \{1,3,4,6\} & S_{13 }& = \{2,3,5,6\}\\
 S_4 & = \{1,2,4,5\} & S_9 & = \{1,3,5,6\} & S_{14} & = \{2,4,5,6\}\\
 S_5 & = \{1,2,4,6\} & S_{10} & = \{1,4,5,6\} & S_{15} &  = \{3,4,5,6\}\\
\end{aligned}
$$
One selection procedure that would satisfy the definition of random sampling is to use a statistical software to generate a random integer between 1 and 15 and to select the corresponding sample. It is easy to check that each element is included in 10 of the 15 samples and thus has a probability of $\frac{10}{15} = \frac{2}{3} > 0$ of being sampled.  If we were to, instead, ask a colleague to arbitrarily choose four integers between one and six and include the corresponding elements in the sample, the same would not apply. Neither would we know how often our colleague would pick each element if we asked her to repeat the process many times; nor can we be sure that each element would be picked at some point with positive probability. Note that the selection probability need not be the same for all elements for a sampling procedure to qualify as random. For example, we could choose a procedure in which the first unit has a greater probability of being sampled than all other units. What matters is that each element's probability of being sampled is *known* to the researcher. 

The core benefit of random sampling is that it makes it possible to draw inferences about the population based on the characteristics of one realized sample. For example, suppose we are interested in estimating the average age of the population and the population distribution of ages is as follows:

```{r, echo = FALSE}
id = c(1,2,3,4,5,6)
age = c(25,18,33, 22,50, 45)

data <- data.frame(Age = age)

knitr::kable(t(data), col.names = id)

```

The average age in the population is $$\mu = \frac{25 + 18 + 33 + 22 + 50 + 45}{6} \approx 32$$. Now, suppose that we draw our random sample of four units and use the average age in the sample as an estimate of the average age in the population. The first thing to note is that the fact that we are basing our estimation on a sample and not the entire population means that our estimate will be prone to error. If we were to select the first of the 15 samples listed above, for example, our estimate would be $$\hat{\mu} = \frac{25 + 18 + 33 + 22}{4} = 25.$$ The difference between the true parameter and our estimate $\mu - \hat{\mu} = 32 - 25 = 7$ stems from what is referred to as *sampling error*. Yet, even though estimates based on a single realized sample are subject to sampling error, the process of random sampling (in combination with the chosen estimation procedure) can ensure that our estimates are correct on average across all possible random samples.

Fiugre x plots what is called the sampling distribution - the distribution of age estimates that results from the 15 possible samples. The red line plots the average estimate across all samples and coincides with the true population paremeter of $\sim 32$. Of course, the fact that we would be correct on average if we repeated the sampling procedure many times and took the average across all resulting estimates says little about how correct our estimates will be given the one realized sample that we will have available. Yet, the beauty of random sampling is that it allows us (in most cases) to obtain estimates of the variability of the sampling distribution.^[Not all sampling designs are measurable, see Kish.]


- Because we know the selection procedure, we can base our inferences on measures of variability that can be computed from the realized sample. [random probability samples are typically measurable, which means uncertainty estimates from the sample alone. ]
- A truly random sample is an ideal that can only be approached. 

2. What distinguishes random sampling and random assignment?
==
- In randomized experiments, we use a random process to assign units from a pool of experimental subjects to several experimental conditions - in the easiest case to a treatment and a control condition. 
- Key characteristic of an experiment: subjects have a known *assignment* probability that lies strictly between 0 and 1. 
- Advantage of random assignment is that it facilitates inferences about causal effects. In many cases, the average causal effect of the treatment on some outcome is the target of inference. 
- Experimental subject pool may or may not be a random sample of a population. In many cases, it is not.
- Combining random sampling with random assignment: first draw a random sample, then assign random sample to treatment and control
  - advantages:
      - way to draw inferences not only about SATE but also about PATE.
      - units that have not been sampled can serve as additional control units in the future

[Maybe mention here the connection between assignment and sampling, i.e. assignment as sampling from treated and control potential outcomes? But maybe this blurs rather than accentuates the distinction.]

3. How to obtain a random sample?
==

- Move from the "target population" to a sampling frame - a list of elements or units of elements
  - sampling frames are rarely perfect, may suffer from over- and undercoverage - see Kish (1965) and Groves et al. (2009) for ways to improve imperfect sampling frames
- Use sampling frame to randomly select elements 
- Different ways to randomly sample elements from a sampling frame (many have analogues in ways in which subjects can be assigned to treatment - see guide on 10 things on randomization)
  - Simple Random Sampling/EPSEM (Equal Probability Selection Method) 
  - Stratification 
  - Clustering
  - Multi-stage sampling
  - Systematic sampling

4. What to do if there does not exist a sampling frame?
==

- In many cases, a sampling frame does not exist. Mostly the case for field experiments in developing country settings.
- In practice, people often rely on some variant of multi-stage area sampling - e.g. randomly select districts, within districts, randomly select villages, within villages, randomly select households, within households, randomly select members
  - Problem 1: lists may exist (e.g. from census or administrative units) all the way to village selection stage, but lists of households in villages are rare in developing country settings. 
    - Popular Solutions:
        - A) Random walk procedure
          - cheap
          - yet,  difficult to implement in practice
          - unlikely to approximate a random sample
        - B) Conduct a listing of households, sample households, conduct a listing of household members and then sample members
          - more expensive, yet note that only households in sampled villages (and members of sampled households) have to be listed
          - still not that easy (e.g. what is a household?)
          - yet, much more likely to approximate a random sample
          - lists can be re-used for some time in the future, esp. in places with low mobility (list as a public good)
  - Problem 2: Boundaries of the smallest area unit (e.g. village) may not be well defined or smallest units may still be too big/impractical
    - Creative solutions:
      - Make your own units (e.g. Scacco in Nigeria or Green et al. in Uganda), for example using satellite imagery 
      - List households within those units
      
5. What to consider when putting a sampling strategy into practice?
==

- Drawing a truly random sample is hard! Many unforeseen problems can occur and these are often context-specific. Hence, pre-testing one's sampling strategy is at least as if not more important than pre-resting one's questionnaire. Examples of difficulties that one may be able to discover and address during a pre-test:
  - Definitions of "dwelling" or "household" can vary across contexts. Important to clarify the definition and find ways to deal with edge cases.
  - Familiarity with and ability to read maps may vary across contexts. When working with satellite imagery, it may be important to highlight landmarks. 
  - When sampling household members, these are often identified by gender and age (first invented by Kish 1965). In some contexts, households members may not know their age or birthday, in which case some other marker should be used.

- Keeping it simple is  an advantage. Sophisticated sampling strategies may not be worth it if they cannot be implemented even though they may bring some gains in precision. Clear instructions to survey staff are very important. 

- It is often helpful to separate out tasks, e.g. at IPA Uganda it is common practice that survey teams comprise ``mobilizers'' who are solely responsible for listing households, drawing the sample of households, sampling household members and making appointments. This is helpful because these sampling-related tasks can be complex and may be too much to bear for enumerators who also have to be familiar with the questionnaire and interviewing techniques. 

6. How does one's sampling strategy affect one's analysis strategy?
==

- Experimentalists are accustomed to the notion that one's random assignment strategy affects one's analysis strategy. The same goes for one's sampling strategy. Two key examples:

A) Weight by the inverse of an element's probability of being sampled if sampling probabilities vary across elements.
  - Arises commonly if one household member is sampled in every household but households are of varying size. 
  - E.g. weighted sample mean as estimator of population mean
  - Same applies to treatment effect estimation in randomized experiments that are based on random samples where sampling probabilities vary across subjects. Estimating the PATE requires weighting by sampling probabilities. Yet, doing so also has costs in terms of precision. Bias will only arise if sampling weights are correlated with treatment effects. Not always clear that weighting is the best strategy. Cite Miratrix et al. 2018 who show that weighting does little to results of survey experiment and suggest post-stratifying on weights in order to reduce loss in precision.
  
B) Adjust variance estimates for clustering. 
  - in treatment effect estimation in randomized experiments that are based on random samples, we may want to cluster at a level higher than that of the level of assignment when sampling was clustered at higher levels (Abadie et al. 2017 WHEN SHOULD YOU ADJUST STANDARD ERRORS FOR CLUSTERING? )

7. How to take into account  variability from both random sampling and random assignment?
==

- A more general point is that if the units in an experiment are a random sample of a larger population, then our realized estimate may deviate from the true PATE for two reasons:
  - 1)  we have drawn one of many possible samples instead of performing our analysis on the entire population,
  - 2) we cannot observe all potential outcomes and have therefore chosen one of many possible ways to assign units to treatment and control. 
  - if we want to make inferences to population quantities, our uncertainty estimates should reflect both kinds of variability
- Randomization inference only considers one kind of variability 
- Combining randomization inference with bootstrapping? [IS THAT A THING?]
-  Aronow/Green/Lee: SHARP BOUNDS ON THE VARIANCE IN RANDOMIZED EXPERIMENTS:
  - Standard Neyman standard errors are conservative if we only presume variation from random assignment, can also be justified if we sample from an infinite superpopulation
  - this paper provides bounds for the case of sampling from a finite population

8. How can sampling help with problems of non-response?
==

- Describe double sampling approach (Coppock et al. 2016)

9. How to sample difficult-to-reach populations?
==

- Difficult to draw a random sample of populations that are rare
- Inferential target is often the prevalence of some characteristic among the target population or the size of the difficult-to-reach population itself
- Respondent-driven-sampling as one solution to this problem
- Procedure: Start with a non-random initial sample, hand out coupons through which respondents in initial sample can recruit more respondents
- The ideas is that conducting many waves reduces the influence of the initial non-random sample
- Still does not yield a probability sample because probabilities of selection are not known
- Various approximations exist, most common one thinks of sampling process as a random walk. Implies that  unconditional probabilities of selection are proportional to number of network ties. The latter can be elicited and  used for weighting.
- This model is known to be false in many ways (e.g. presumes sampling with replacement). Gile et al. 2018 describe a range of subsequent approaches that seek to relax the problematic assumptions. 

10. What else to consider when designing a sampling strategy for a randomized experiment?
==

- A random sample is often not possible and experiments rely on convenience samples. 
- Nonetheless, there are important considerations to take into account when designing a sampling strategy.
- Most importantly, maintain symmetry across treatment and control. For example, suppose an experiment evaluates the effect of community meetings. Sampling respondents from a radius around the community hall where the meeting took place sounds like a good strategy. Yet, it only is if there are community halls in control group villages in which the community meeting would have taken place if the village had been assigned to treatment. Otherwise, the same sampling strategy cannot be implemented in treatment and control which may lead to an exclusion restriction violation. 
  - There may be more subtle versions of this. Generally, great to sample units prior to assignment. When sampling units post assignment, make sure that sampling is unlikely to be affected by treatment. 
- You may want to sample in a way to avoid spillovers - e.g. if households are the unit of randomization, you may want to impose a distance constraint to avoid spillover. 



References
==
