---
title: "10 Things You Need to Know About Multiple Comparisons"
output: html_document
Author: NA
---


Abstract
==
The “Multiple Comparisons Problem” is the problem  that standard statistical procedures can be misleading when researchers conduct a large group of hypothesis. When a research has multiple “bites at the apple,” the chances are that some finding will appear “significant” even when there’s nothing going on.

Classical hypothesis tests assess statistical significance by calculating the probability under a null hypothesis of obtaining estimates as large or larger as the observed estimate. When multiple tests are conducted, however, classical p-values are incorrect — they no longer reflect the true probability under the null.

This guide will help you guard against drawing false conclusions from your experiments. We focus on the big ideas and provide examples and tools that you can use in R.


Almost every social science experiment faces a multiple comparisons problem
==
Typically, researchers are not interested in just one treatment versus control comparison per experiment. There are three main ways that comparisons proliferate:

1. **Multiple treatment arms.** When an experiment has n treatment arms, there are n(n-1)/2 possible comparisons.
2. **Heterogeneous treatment effects.** Often, we are interested in whether the treatment has different impacts on different subgroups.  For example, a treatment might be more effective for women than for men.
3. **Multiple estimators.** Often, experimenters will apply multiple estimators to the same dataset: for example, difference-in-means and covariate adjustment.
There is of course nothing wrong with employing multiple treatment arms, exploring treatment effect heterogeneity, or using multiple estimators of the treatment effect.  However, these design and analysis choices sometimes require that researchers correct their statistical tests to account for multiple comparisons.

These concerns are especially problematic when making a “family claim,” that is, when you are summarizing a series of results.  For example, a family claim might be that treatments A, B, C, and D had no effect, but treatment E did.  Or, similarly, the treatment had no effect among group 1, group 2, or group 3, but had a strong effect among group 4.

The multiple comparisons problem is related to, but different from, the problem of “fishing”.  Fishing occurs when an unscrupulous analyst conducts many tests but only reports the “interesting” ones. In essence, fishing withholds the necessary information we would need in order to correct for multiple comparisons.

2 Why multiple comparisons are a problem
==
In classical hypothesis testing, the “alpha level” describes how willing the researcher is to make a certain kind of mistake — a so-called Type I error. A Type I error occurs when a researcher falsely concludes that an observed difference is “real,” when in fact there is no difference. In many social science applications, the alpha level, or Type I error rate, is set to 0.05. This means that the researcher is willing to commit a Type I error 5% of the time.

But when we move to the world of multiple comparisons, this simple testing framework is no longer sufficient. We are trying to avoid the scientific error of falsely concluding that an effect is practically or substantively meaningful — but if we apply the classical hypothesis testing framework without addressing multiple comparisons, we are much more likely to commit such an error.

In this guide, we will describe three main approaches for addressing the multiple comparisons problem:

1. *p*-value adjustments. Statisticians have derived a number of corrections that can guard against multiple comparisons mistakes. As described in the next section, these corrections control either the *Family-Wise Error Rate* (FWER) or the *False Discovery Rate* (FDR).  Most of these adjustments apply a simple formula to a series of “raw” p-values; we will also describe a simulation method that can take account of features of a specific research setting.
2. Pre-analysis plans. These plans are a powerful design-based tool for “calling your shot” so to speak.
3. Replication. If we are concerned that a finding is simply an artifact of sampling variability that we happened to discover because of a blind application of classical hypothesis testing, then the best way to resolve the question is to conduct the experiment again.

3 Don't mix up the FWER and FDR!
==
In the world of multiple testing, the Type I error rate might refer to one of two things: the Family-Wise Error Rate (FWER) or the False Discovery Rate (FDR).

The FWER is the probability of incorrectly rejecting even one null hypothesis. Suppose we have three null hypotheses, all of which are true. When the null hypothesis is true, but we nevertheless reject it in favor of some alternative, we commit a Type I error. If we set alpha (the Type I error rate) to be 0.05, we have a [$1−(1−0.05)3=14.2%$] chance of rejecting at least one of them. In order to control the FWER (i.e., reduce it from 14.2% back down to 5%), we need to employ a correction. We’ll explore three ways to control the FWER (Bonferroni, Holm, and simulation ) in the sections below.

The FDR is subtly different. It is the proportion of false discoveries among all tested (true) null hypotheses. For example, if you are testing 60 hypotheses, a procedure that controls the FDR (at alpha=0.05) will ensure that no more than 3 hypotheses are falsely rejected. The FDR is less stringent than the FWER, but may be more appropriate in some research situations.

4 The Bonferroni correction is too extreme
==
The Bonferroni correction is a commonly-used approach for addressing the multiple comparisons problem, partly because of its simplicity. If you conduct k tests, the target significance level should be alpha/k, or, equivalently, you multiply your *p*-values by k, and apply the standard alpha level. (The trouble with multiplying the *p*-values is sometimes you end up with values over one, rendering the interpretation of the *p*-values incoherent.)

For example, suppose you conduct an experiment that has 3 dependent variables. You conduct three difference-in-means tests that yield the following classical *p*-values: 0.004, 0.020, and 0.122. If your alpha level is the standard 0.05 threshold, then you would usually declare the first two tests statistically significant and the last test insignificant. The Bonferroni correction, however, adjusts the target *p*-value to 0.05/3 = 0.016. We then declare only the first test to be statistically significant.

The Bonferroni correction works under the most extreme circumstances, that is, when all k tests are independent from one another. To see how this works, imagine we are testing three true null hypotheses using a classical alpha level of 0.05. Each test, therefore has a 5% chance of yielding the wrong answer that the null hypothesis is false.

But our chances of making at least one mistake are much greater than 5% because we have three chances to get it wrong. As above, this probability is in fact  [$1 - (1 - 0.05)^3 = 14.2%$] . If we use the Bonferroni correction, however, our chances of getting it wrong fall back to our target alpha value:  [$1 - (1 - 0.05/3)^3 \approx 0.05$] .

This correction works in the worst-case scenario that all tests are independent. But in most cases, tests are not independent. That is, if your treatment moves outcome A, it probably moves outcome B too, at least a little. So what tends to happen is, researchers report that their results “withstand” Bonferroni when they are extremely strong, but decry Bonferroni as too extreme when the results are weaker.

Instead of using the Bonferroni correction, you can use the Holm correction.  It is strictly more powerful than Bonferroni, and is valid under the same assumptions. It also controls the FWER. Suppose you have  [m]  *p*-values.  Order them from smallest to largest. Find the smallest p-value that satisfies this condition: $pk>\frac{α}{m+1−k}$, where  k is the *p*-value’s index. This and all larger *p*-values are insignificant; all smaller *p*-values are significant.

Taking our three *p*-values from above: 0.004, 0.020, and 0.122:
$$0.004<\frac{0.05}{3+1−1}=0.017$$
$$0.020<\frac{0.05}{3+1−2}=0.025$$
$$0.122>\frac{0.05}{3+1−3}=0.050$$

Under the Holm correction, the first two tests are significant, but the last test is not.