---
output: 
  html_document:
    toc: true
    theme: journal
---

<!-- title: "10 Things You Need to Know About Causal Inference" -->
<!-- author: "Methods Guide Author: Macartan Humphreys" -->

Resumen
==

El filósofo David Lewis describió la causalidad como "algo que marca la diferencia, y esa diferencia que hace, debe ser la diferencia entre lo que fue y lo que hubiera sido sin ese algo".[^1] Esta es la interpretación que dan a la causalidad la mayoría de los experimentalistas. Aunque la definición parece simple, tiene muchas implicaciones sutiles. Aquí les presentamos diez ideas implícitas en esta noción de causalidad que son importantes para el diseño de investigación.^[Autor: Macartan Humphreys. Revisiones menores: Winston Lin y Donald P. Green, 24 de junio de 2016. Revisiones MH 6 de enero de 2020. Revisiones Anna Wilke de mayo de 2021. Esta guía es un documento dinámico y está sujeta a actualización por parte de los miembros de EGAP; los colaboradores enumerados no son responsables de las ediciones posteriores.]


[^1]: Lewis, David. "Causation." The journal of philosophy (1973): 556-567.

1. Una afirmación causal es un enunciado sobre lo que no sucedió
==

Para la mayoría de investigadores que realizan experimentos, el enunciado "$X$ causó $Y$" significa que $Y$ ocurrió *y*  que no habría ocurrido si $X$ no hubiera estado presente. Esta definición requiere que tengamos una noción de lo que podría haber sucedido, pero no sucedió.[^2] De manera similar, el "efecto" de $X$ en $Y$ se considera la diferencia entre el valor que $Y$ habría tomado dado un valor de $X$ y el valor que $Y$ habría tomado dado otro valor de $X$. Debido al enfoque en la diferencia de los resultados, este enfoque a veces se conoce como el enfoque de causalidad basado en "hacer diferencias" o en lo "contrafactual".

__Nota técnica:__ Los estadísticos emplean el marco de "salidas potenciales" para describir las relaciones contrafactuales. En este marco, dejamos que $Y_i(1)$ denote el valor que la unidad $i$ tomaría bajo la condición uno (por ejemplo, si la unidad $i$ recibió un tratamiento) y $Y_i(0)$ el valor que habría sido observado en otra condición (por ejemplo, si la unidad $i$ no recibió el tratamiento). Un efecto causal del tratamiento para la unidad $i$ puede ser una simple diferencia de las salidas potenciales $τ_i = Y_i(1)−Y_(0)$. Un tratamiento tiene un efecto causal (positivo o negativo) en $Y$ para la unidad $i$ si $Y_i (1) ≠ Y_i (0)$.



[^2]: Holland, Paul W. "Statistics and causal inference." Journal of the American Statistical Association 81.396 (1986): 945-960.

2. No hay relación causal sin manipulación.
==

La definición "contrafactual" de causalidad requiere que uno sea capaz de pensar qué valores podemos observar en diferentes condiciones. ¿Cómo serían las cosas si se eligiera un partido en lugar de otro? Las declaraciones causales cotidianas a menudo no cumplen con este requisito en alguna de estas dos formas:

* Primero, algunas declaraciones no especifican condiciones contrafactuales claras. Por ejemplo, la afirmación de que "la recesión fue causada por Wall Street" no apunta a un contrafactual obvio: ¿debemos considerar si habría habido una recesión si Wall Street no existiera? ¿O es la afirmación realmente una afirmación sobre acciones particulares que Wall Street podría haber tomado pero no lo hizo? Si es así, ¿qué acciones? Es difícil evaluar la validez de tales declaraciones. Además, puede depender de qué condiciones contrafactuales estén implícitas en una afirmación.


* En segundo lugar, algunos enunciados implican condiciones contrafactuales que no son posibles de imaginar. Por ejemplo, la afirmación de que Peter consiguió el trabajo porque es Peter implica una consideración de lo que habría sucedido si Peter no fuera Peter. Alternativamente, la afirmación de que Peter consiguió el trabajo porque es un hombre requiere considerar a Peter como algo diferente de un hombre. El problema es que los contrafactuales en estos casos implican un cambio no solo en la condición que enfrenta un individuo sino en el propio individuo.

Para evitar estos problemas, algunos estadísticos instan a restringir las afirmaciones causales a los tratamientos que pueden manipularse, al menos en la imaginación, y no necesariamente en la práctica.[^11] Por ejemplo, si bien podríamos tener dificultades con la afirmación de que Peter consiguió el trabajo porque es hombre, no tendríamos las mismas dificultades con la afirmación de que Peter consiguió el trabajo porque la agencia de contratación pensó que era hombre



[^11]: Holland, Paul W. "Statistics and causal inference." Journal of the American Statistical Association 81.396 (1986): 945-960.


3. Las causas no tienen por qué ser rivales.
==
Aunque nos podemos centrar en el efecto de una sola causa $X$ en un variable de interés $Y$, generalmente no esperamos que $Y$ tenga solo una causa.[^5] Además, si sumamos los efectos causales de diferentes causas, no hay razón para esperar que sumen el 100%. Por lo tanto, no tiene mucho sentido tratar de "distribuir" los resultados entre diferentes factores causales. En otras palabras, las causas no tienen por qué ser rivales. La Asociación Nacional del Rifle de Estados Unidos sostiene, por ejemplo, que las armas no matan a la gente, la gente mata a la gente. Esa afirmación no tiene mucho sentido en el marco hipotético. Quita las armas y no tendrás muertes por heridas de bala. Entonces las armas son una causa. Quita a la gente y tampoco tendrás muertes por heridas de bala, por lo que las personas también son una causa. Dicho de otra manera, estos dos factores son simultáneamente causas de los mismos resultados.


[^5]: Esto se conoce a veces como el "Problema de las causas excesivas".


4. $X$ puede causar $Y$ incluso si $X$ no es una condición necesaria o una condición suficiente para que $Y$ ocurra.
==
A menudo hablamos de relaciones causales en términos deterministas. Incluso la cita de Lewis en la parte superior de esta página parece sugerir una relación determinista entre causas y efectos. A veces se piensa que las relaciones causales implican condiciones necesarias (para $Y$ que ocurra, $X$ tiene que suceder ); a veces se piensa que tales relaciones implican condiciones suficientes (si ocurre $X$, entonces ocurre $Y$). Pero una vez que hablamos de múltiples unidades, hay al menos dos formas en las que podemos pensar en que $X$ causa $Y$ incluso si $X$ no es una condición necesaria ni suficiente para $Y.$ La primera es reinterpretar todo en términos probabilísticos: que $X$ cause $Y$, simplemente quiere decir que la probabilidad de $Y$ es mayor cuando $X$ está presente. Otra forma es permitir contingencias. Por ejemplo, $X$ puede causar $Y$ si la condición $Z$ está presente, pero no de otra manera.[^9]

[^9]: De acuerdo a Mackie, a veces se invoca la idea de condiciones "INUS" para capturar la dependencia de las causas de otras causas. Según esta explicación, una causa puede ser parte Insuficiente pero Necesaria de una condición que en sí misma es Innecesaria pero Suficiente. Por ejemplo, marcar un número de teléfono es una causa de contacto con alguien, ya que tener una conexión y marcar un número es suficiente (S) para hacer una llamada telefónica, mientras que marcar solo sin una conexión no sería suficiente (I), ni tener una conexión (N). Por supuesto, hay otras formas de contactar a alguien sin hacer llamadas telefónicas (U). Mackie, John L. "El cemento del universo". Londres: Oxford Uni (1974).




5. Existe un problema fundamental de la inferencia causal
==
Si los efectos causales son enunciados sobre la diferencia entre lo que sucedió y lo que podría haber sucedido, entonces no los podemos medir. Malas noticias. De manera prospectiva, puede organizar las cosas para que pueda observar lo que sucede si alguien recibe un tratamiento o lo que sucede si no recibe el tratamiento. Sin embargo, para la misma persona nunca podrá observar ambos resultados y, por lo tanto, tampoco la diferencia entre ellos. Esta incapacidad para observar efectos causales a nivel de la unidad de estudio a menudo se denomina "problema fundamental de la inferencia causal".


6. Usted puede estimar el efecto causal promedio aun cuando no pueda observar ningún efecto causal individual.
==
Aunque no pueda observar si $X$ causa $Y$ para una unidad determinada, sí es posible determinar si $X$ causa $Y$ en promedio. La idea clave aquí es que el efecto causal promedio es igual a la diferencia entre la variable de resultado promedio para todas las unidades, si todas están en la condición de control y la variable de resultado promedio para todas las unidades si todas  están en la condición de tratamiento. Muchas estrategias para la identificación causal (ver [10 estrategias para determinar si X causó Y](http://egap.org/resource/10-strategies-for-figuring-out-if-x-caused-y)) se enfocan en formas de aprender acerca de estas salidas potenciales promedio.^[__Nota técnica:__ La idea técnica clave es que la diferencia de promedios es la misma que el promedio de diferencias. Es decir, usando el "operador de expectativas", $𝔼(τ_i) = 𝔼 (Y_i (1) −Y_i (0)) = 𝔼(Y_i (1)) - 𝔼(Y_i (0))$. Los términos dentro del operador de esperanzas en la segunda cantidad no se pueden estimar, pero los términos dentro de los operadores de expectativas en la tercera cantidad si se pueden ser estimados[^3] Vea la ilustración [aquí] (https://raw.githubusercontent.com/egap/ guías-métodos / maestro / inferencia-causal / PO.jpg).]




[10 cosas que debe saber sobre las pruebas de hipótesis](https://egap.org/resource/10-things-to-know-about-hypothesis-testing/) nos muestra cómo podemos aprender acerca de efectos causales individuales en vez de efectos promediodato el problema fundamental de la inferencia causal.

[^3]: Holland, Paul W. "Statistics and causal inference." Journal of the American Statistical Association 81.396 (1986): 945-960.

7. La estimación del efecto causal promedio no requiere que los grupos de tratamiento y control sean idénticos.
==
Una estrategia que la gente usa para aprender acerca del efect causal promedio es crear grupos de tratamiento y control a través de la aleatorización (ver [10 estrategias para determinar si X causó Y](http://egap.org/resource/10-strategies-for- determinar-si-x-causó-y)). Es común que algunos investigadores se  preocupen por que los grupos de tratamiento y control resultantes no sean similares en dimensiones relevantes.

La buena noticia es que la razón por la cual las diferencias en los resultados promedio entre los grupos de control y tratamiento asignados aleatoriamente capturan los efectos promedio del tratamiento (en valor esperado a través de aleatorizaciones repetidas dentro del mismo grupo de unidades) *no* se basa en que los grupos de tratamiento y control sean similares en las características observadas. Sino que se basa únicamente en la idea de que, en promedio, los resultados en los grupos tratados y de control capturarán los resultados promedio para todas las unidades en el grupo experimental si estuvieran, respectivamente, en tratamiento o en control. En la práctica, los grupos de tratamiento y de control no serán idénticos.[^10]

[^10]: Por esta razón usar las pruebas $t$ para verificar si "la asignación aleatoria funcionó bien" no tiene mucho sentido, al menos si se sabe que se siguió una procedimiento aleatorio: por simple chance, 1 de cada 20 de esas pruebas mostrará diferencias estadísticamente detectables entre los grupos tratados y de control. Si existen dudas sobre si la asignación aleatoria se realizó correctamente, estas pruebas se pueden utilizar para probar la hipótesis de que los datos se generaron efectivamente mediante un procedimiento aleatorio. Esta última razón para las pruebas de aleatorización puede ser especialmente importante en experimentos de campo donde las cadenas de comunicación entre la persona que crea los números aleatorios y la persona que implementa la asignación del tratamiento son largas y complejas.


8. Correlación no es igual a causalidad.
==
Una correlación entre $X$ y $Y$ es un enunciado sobre las relaciones entre los valores reales de estas variables y no sobre la relación entre los valores reales y los valores contrafactuales. Entonces las afirmaciones sobre causas y correlaciones no tienen mucho que ver entre sí. Las correlaciones positivas pueden ser consistentes con efectos causales positivos,  efectos causales nulos o incluso con efectos causales negativos. Por ejemplo, tomar medicamentos para la tos se correlaciona positivamente con la tos, pero es de esperar que tenga un efecto causal negativo sobre la tos.^[__Nota técnica:__ Sea $D_i$ un indicador de si la unidad $i$ ha recibido un tratamiento o no. Entonces la diferencia en los resultados promedio entre los que reciben el tratamiento y los que no lo reciben se puede escribir como $\frac{∑_i D_i × Y_i (1)} {∑_iD_i} - \frac {∑_i(1 − D_i) × Y_i (0)}{∑_i (1 − D_i)}$. Sin información sobre cómo se asignó el tratamiento, no hay mucho por decir sobre si esta diferencia es un buen estimador del efecto promedio del tratamiento. Es decir, de la diferencia en las salidas potenciales promedio de las unidades en el grupo de tratamiento y control para todas las unidades. Lo que importa es si $\frac{∑_i D_i × Y_i (1)} {∑_iD_i $ es una buena estimación de $\frac{∑_i 1 × Y_i (1)} {∑_i1}$ y si $\frac{∑_i (1 − D_i) × Y_i (0)}{∑_i(1 − D_i)}$ es una buena estimación de $\frac{∑_i 1 × Y_i (0)} {∑_i1}$. Este puede ser el caso si los que recibieron tratamiento son una muestra representativa de todas las unidades, pero de lo contrario no hay razón para esperar que así sea.]



9. Si usted sabe que, en promedio, $A$ causa $ B $ y $B$ causa $C$, esto no significa que, en promedio, $A$ cause $C$.

==
Se podría esperar que si $A$ causa $B$ y $B$ causa $C$, entonces $A$ causa $C$.[^12] Pero no hay razón para creer que las relaciones causales promedio sean transitivas.  Para entender por qué, imagine que $A$ causó $B$ en los hombres pero no en las mujeres y $B$ causó $C$ en las mujeres pero no en los hombres. Entonces, en promedio, $A$ causa $B$ y $B$ causa $C$, pero es posible que no haya nadie para quien $A$ tenga un efecto en $C$ mediado por $B$.

[^ 12]: Entiéndase la expresión "$A$ causa $B$, en promedio" como "el efecto promedio de $A$ sobre $B$ es positivo".



10. Es más fácil aprender sobre los "efectos de las causas" que aprender sobre las "causas de los efectos".
==
Aunque puedan parecer dos formas de decir exactamente lo mismo, existe una diferencia entre comprender cuál es el efecto de $X$ en $Y$ (los "efectos de una causa") y si  *el valor que tomó $Y$* se debió a $X$ (la "causa de un efecto").[^6] Considere el siguiente ejemplo. Supongamos que realizamos un experimento con una muestra que contiene el mismo número de hombres y mujeres. El experimento asigna aleatoriamente a hombres y mujeres a un tratamiento binario $X$ y mide una variable de interés binaria $Y$. Además suponga que $X$ tiene un efecto positivo de 1 para todos los hombres, es decir, el resultado potencial del control de los hombres es cero ($Y_i(0) = 0$) y la salida potencial cuando son tratados es uno ($Y_i(1) = 1$). Para todas las mujeres, $X$ tiene un efecto negativo de $-1$, es decir, la salida potencial de las mujeres bajo el control es uno ($Y_i (0) = 1 $) y su salida potencial cuando son tratadas es cero ($Y_i (1) = 0$)  En este ejemplo, el efecto promedio de $X$ en $ Y $ es cero. Pero la razón para que los participantes en el grupo de tratamiento tengan $Y = 1$,  es *porque* $X = 1$. De manera similar, todos los participantes en el grupo de tratamiento con $Y = 0$, tienen  $Y = 0$ *porque* $X = 1$. Los experimentos nos permiten obtener una respuesta exacta a la pregunta sobre los "efectos de una causa", pero en general no es posible obtener una respuesta exacta a la pregunta sobre la "causa de un efecto".[^ 7]


[^ 6]: A veces se reinterpreta la pregunta "causas de los efectos" en el sentido de: ¿cuáles son las causas que tienen efectos sobre las variable de resultado? Véase Andrew Gelman and Guido Imbens, "Why ask why?
Forward causal inference and reverse causal questions", NBER Working Paper No. 19614 (Nov. 2013).
[^7]: Ver, por ejemplo, Tian, J., Pearl, J. 2000. “Probabilities of Causation: Bounds and Identification.” Annals of Mathematics and Artificial Intelligence 28:287–313.
.
